// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.3
// source: service.proto

package url_service_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShortenerUrlClient is the client API for ShortenerUrl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortenerUrlClient interface {
	CreateShortenUrl(ctx context.Context, in *CreateShortenUrlRequest, opts ...grpc.CallOption) (*CreateShortenUrlResponse, error)
	GetShortenUrl(ctx context.Context, in *GetShortenUrlRequest, opts ...grpc.CallOption) (*GetShortenUrlResponse, error)
}

type shortenerUrlClient struct {
	cc grpc.ClientConnInterface
}

func NewShortenerUrlClient(cc grpc.ClientConnInterface) ShortenerUrlClient {
	return &shortenerUrlClient{cc}
}

func (c *shortenerUrlClient) CreateShortenUrl(ctx context.Context, in *CreateShortenUrlRequest, opts ...grpc.CallOption) (*CreateShortenUrlResponse, error) {
	out := new(CreateShortenUrlResponse)
	err := c.cc.Invoke(ctx, "/ShortenerUrl/CreateShortenUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerUrlClient) GetShortenUrl(ctx context.Context, in *GetShortenUrlRequest, opts ...grpc.CallOption) (*GetShortenUrlResponse, error) {
	out := new(GetShortenUrlResponse)
	err := c.cc.Invoke(ctx, "/ShortenerUrl/GetShortenUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenerUrlServer is the server API for ShortenerUrl service.
// All implementations must embed UnimplementedShortenerUrlServer
// for forward compatibility
type ShortenerUrlServer interface {
	CreateShortenUrl(context.Context, *CreateShortenUrlRequest) (*CreateShortenUrlResponse, error)
	GetShortenUrl(context.Context, *GetShortenUrlRequest) (*GetShortenUrlResponse, error)
	mustEmbedUnimplementedShortenerUrlServer()
}

// UnimplementedShortenerUrlServer must be embedded to have forward compatible implementations.
type UnimplementedShortenerUrlServer struct {
}

func (UnimplementedShortenerUrlServer) CreateShortenUrl(context.Context, *CreateShortenUrlRequest) (*CreateShortenUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShortenUrl not implemented")
}
func (UnimplementedShortenerUrlServer) GetShortenUrl(context.Context, *GetShortenUrlRequest) (*GetShortenUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShortenUrl not implemented")
}
func (UnimplementedShortenerUrlServer) mustEmbedUnimplementedShortenerUrlServer() {}

// UnsafeShortenerUrlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortenerUrlServer will
// result in compilation errors.
type UnsafeShortenerUrlServer interface {
	mustEmbedUnimplementedShortenerUrlServer()
}

func RegisterShortenerUrlServer(s grpc.ServiceRegistrar, srv ShortenerUrlServer) {
	s.RegisterService(&ShortenerUrl_ServiceDesc, srv)
}

func _ShortenerUrl_CreateShortenUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShortenUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerUrlServer).CreateShortenUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShortenerUrl/CreateShortenUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerUrlServer).CreateShortenUrl(ctx, req.(*CreateShortenUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortenerUrl_GetShortenUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShortenUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerUrlServer).GetShortenUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShortenerUrl/GetShortenUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerUrlServer).GetShortenUrl(ctx, req.(*GetShortenUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortenerUrl_ServiceDesc is the grpc.ServiceDesc for ShortenerUrl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortenerUrl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ShortenerUrl",
	HandlerType: (*ShortenerUrlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShortenUrl",
			Handler:    _ShortenerUrl_CreateShortenUrl_Handler,
		},
		{
			MethodName: "GetShortenUrl",
			Handler:    _ShortenerUrl_GetShortenUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
